import binascii
import itertools
import random
from pathlib import Path

# Generated wav files will be saved there
TONES_PATH = Path(__file__).resolve().parent.parent / "tones"

# File generated by ANU Quantum randomiser. File contains 2000 characters, "1" or "0"
# Source: https://qrng.anu.edu.au/contact/faq/#downloads
QRND_DATA_PATH = Path(__file__).resolve().parent / "data" / "anu_qrng_set.txt"

# Blocks for building wav files, hex
# Wav files characteristics: 8kHz, 16bit, Square wave, 1000Hz base tone
WAV_META = binascii.unhexlify("52494646a4bb000057415645666d74201000000001000100401f0000803e0000020010006461746180bb0000")
TONE_SQR = binascii.unhexlify("000078840000897b")
TONE_NUL = binascii.unhexlify("0000000000000000")

# Set to True if you want noise over 500Hz tone
TONE500 = False

random.seed(0)


# Generating 9 wav files with different level of noise
for y in range(1, 10):
    file_path = TONES_PATH / f"{y}.wav"
    noise_count = 0
    with open(file_path, "wb") as wav_file:
        wav_file.write(WAV_META)
        for _ in range(2000):
            if TONE500:
                wav_file.write(TONE_SQR)
            calc_random = random.random() * 10  # Deterministically randomised noise
            if y > calc_random:
                wav_file.write(TONE_SQR)
                noise_count += 1
            else:
                wav_file.write(TONE_NUL)
    print(y, noise_count)

# Generating a wav file with a noise taken from quantum randomiser:
file_path = TONES_PATH / "x.wav"
noise_count = 0
with open(QRND_DATA_PATH) as qrnd_set, open(file_path, "wb") as wav_file:
    wav_file.write(WAV_META)
    for c in itertools.chain.from_iterable(qrnd_set):
        if TONE500:
            wav_file.write(TONE_SQR)
        if c == "1":
            wav_file.write(TONE_SQR)
            noise_count += 1
        else:
            wav_file.write(TONE_NUL)
print("x", noise_count)
